### ISSUE TITLE
Server stops :-/

### ISSUE THREAD

**Issue by bioryb** [Depado/goploader#33]
Hi once again :)
Because I wanted to change some parts of the start page (text, maybe Logo, color) I compiled a version of goploader instead of using the standalone binary. Everything looks good, but when I start goploader it does one run and exists immediately. So this is no standalone version? How can I create one?

```
DEBUG |     server | 2016/06/10 - 12:04:58 |                 | Started Initialize on statistics object
 INFO |     server | 2016/06/10 - 12:04:58 |                 | Total   2 (5.4GB)
 INFO |     server | 2016/06/10 - 12:04:58 |                 | Current 0 (0)
DEBUG |     server | 2016/06/10 - 12:04:58 |                 | Done Initialize on statistics object
 INFO |     server | 2016/06/10 - 12:04:58 |                 | Started goploader server on port : 80
 INFO | monitoring | 2016/06/10 - 12:04:58 |                 | Started Monitoring
DEBUG | monitoring | 2016/06/10 - 12:04:58 |                 | Started Monit on Resources
DEBUG | monitoring | 2016/06/10 - 12:04:58 |                 | Serving 0 (0) files
DEBUG | monitoring | 2016/06/10 - 12:04:58 |                 | Done Monit on Resources (2.337783ms)
DEBUG |     server | 2016/06/10 - 12:04:58 |                 | Loaded templates from "templates" box
DEBUG |     server | 2016/06/10 - 12:04:58 |                 | Loaded assets from "assets" box

```

Thanks in advance

**Comment by bioryb** [comment]
Sorry, my fault.

Permission issue.

**Comment by Depado** [comment]
You don't have any error message ? 
It also depends on how you compiled it. I don't know if I have put the instructions somewhere or not. The simplest fix possible would be to grab the non-standalone version which contains the binary, the `assets` and `templates` folders which you can freely modify. Otherwise I'd love some more information. 

If you wish to create yourself a `standalone verson` you have to do the following steps :

- Modify the stuff in `assets` or `templates` dirs
- `rice embed-go`
- `go build`

**Comment by Depado** [comment]
I'm glad you fixed it, but you should still get an error. Did you get an error message ? Otherwise that's an issue other people could have.

**Comment by Depado** [comment]
That's a bug if you didn't get any ouput. I see how to fix that.
