### ISSUE TITLE
Proxy with Apache

### ISSUE THREAD

**Issue by Fastidious** [Depado/goploader#46]
Proxy with Apache allows me to upload fine . But on download, the link to the file goes to `http://example.com:8008/filename`, which isn't exposed (because it is proxying).

**Comment by Depado** [comment]
Hi, and thanks for your feedback.
Could you check if your issue is related to #41 ?
Also if you use the latest version, there should be a setting called `append_port` which role is to add the port to the returned URL in case there is no reverse proxy in place. Can you make sure this is set to `false` in your `conf.yml` file ?

**Comment by Fastidious** [comment]
@Depado setting `append_port` to `false` fixed this. Thanks!

**Comment by Depado** [comment]
No problem, the doc is a bit outdated ! My bad 😞
