### ISSUE TITLE
Question: Using a database on another server

### ISSUE THREAD

**Issue by Glubb** [Depado/goploader#50]
What would be the method of using a database on another server?

**Comment by Depado** [comment]
Hi there,
At the moment this is not possible since I'm using BoltDB, and there's no protocol to access a BoltDB file remotely. 
A solution would be to change completely the database I'm using for one that can be on a different server. There was an implementation using Gorm (which is an agnostic ORM, so you could use MySQL or PostgreSQL) at one point in the Git history, you could try to retrieve that commit where I decided to move from Gorm to Bolt and use this as a base to use a PostgreSQL database or something like that.
